using System;
using System.Collections.Generic;
using TeamX.Database;
using TeamX.Models;
using TeamX.Services;
using TeamX.Utils;
using Xamarin.Forms;

namespace TeamX
{
    public partial class ForgotPassword : ContentPage
    {
        IUserService US;

        public ForgotPassword()
        {
            InitializeComponent();
            background.Source = ImageSource.FromResource("TeamX.immagini.home.jpg");

            US = new UserService();
        }




        async void Enter_Pressed(object sender, System.EventArgs e)
        {
            //Validate
            if (!Validate(EmailorNameEntry.Text))
            {
                await DisplayAlert("Error", "Please insert a valid email", "OK");
                return;
            }

            

            //get and update user
            User user = US.GetUser(US.FindUserByEmail(EmailorNameEntry.Text));
            if (user == null)
            {
                await DisplayAlert("Error", "This email has never been used before", "OK");
                return;
            }
            var pwd = Generator.GeneratePWD();
            user.Pwd = pwd;
            US.UpdateUser(user);


            //now send email
            Mailer.SendPasswordEmail(user.Email, user.NickName, pwd);
            Email_Sent();

            //now go to login
            await Navigation.PushAsync(new LoginPage());
        }

        private bool Validate(string email)
        {
            if (string.IsNullOrWhiteSpace(email) || !Validator.ValidateEmail(email)) return false;

            return true;
        }

        private async void Email_Sent()
        {
            await DisplayAlert("Password sent", "An autogenerated password has been sent to your email.", "OK");
            return;
        }
       
    }
}
